### ISSUE TITLE
USB serial support

### ISSUE THREAD

**Issue by That-Dude** [supergrub/supergrub#100]
Hi, I see that you have serial support for the motherboard UART(s) but would it be possible to also supoort FTDI USB serial?

Grub has a module for this, and I see it on the SuperGrub2 USB, but when I attempt `insmod usbserial_ftdi` I get an error `disk 'hd0,msdos' not found`

My experience of grub is very limited, I was using this info I found on the grub wiki:
<hr>
To enable serial, first find out the name of your usb serial port trough:

```
insmod nativedisk # needed not to get the disk disapearing when insmoding the *hci
insmod ehci
insmod ohci
insmod uhci
insmod usb
insmod usbserial_pl2303
insmod usbserial_ftdi
insmod usbserial_usbdebug
terminal_output
```
The terminal_output command should print it:

```
grub> terminal_output 
Active output terminals:
serial_usb1 gfxterm 
Available output terminals:
console vga_text serial 
```
Here we can see "serial_usb1" so we now know that its name is usb1
Then add the following on top of your grub.cfg:

```
insmod nativedisk
insmod ehci
insmod ohci
insmod uhci
insmod usb
insmod usbserial_pl2303
insmod usbserial_ftdi
insmod usbserial_usbdebug
serial --speed=115200 --word=8 --parity=no --stop=1 usb1
terminal_output --append serial_usb1
terminal_input --append serial_usb1
```
The following chips/protocols are supported:

usbdebug
ftdi
pl2303

**Comment by adrian15** [comment]
Which specific Super Grub2 Disk download are you using?

I'm not very sure about this. The thing is that drive where Super Grub2 Disk files are should not disappear when you run all of those commands.

Once you manage to do so it's just asking me to add an option to ease those commands although I'm not sure... I mean... not many people ask for it... so... if it's very difficult then I might just pass on it.

**Comment by adrian15** [comment]
There has not been any more feedback into this issue when the reporter was asked to provide feedback.

Hence we are closing this bug.
