### ISSUE TITLE
hybrid_i386_pc/configure' does not exist

### ISSUE THREAD

**Issue by andreyvatoropinit** [supergrub/supergrub#101]
```
Have you run: ./grub-build-001-prepare-build ?
and: ./grub-build-002-clean-and-update ?
and: ./grub-build-003-build-all ?
```

Good day! i try to build this. but it is not working.
Can anybody tell me what should i do ?

**Comment by adrian15** [comment]
You can check https://github.com/supergrub/supergrub/blob/6dbc8bb1dc770bc2d0a363e358847630353deca1/INSTALL.md which will point you to Docker although manual build should also work too.

**Comment by adrian15** [comment]
If you still have the problem please open a new issue explaining exactly what were the commands that you were using.
I feel like your first issue lacked them.

Closing this issue.
