### ISSUE TITLE
Boot Tails ISO / Debian-signed GRUB binaries

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#105]
Hi! I found a case where my own GRUB project fails, and SGD 2.04s2-beta2 does as well: Booting [the Tails ISO](https://mirrors.wikimedia.org/tails/stable/tails-amd64-6.2/tails-amd64-6.2.iso). Their GRUB config says:

```text
# The Debian-signed GRUB binaries have the path of this very configuration file
# (/EFI/debian/grub.cfg) hardcoded. Let's use it instead of adding layers
# of indirection.
```

so it seems that by detecting `(isoloop_cfg)/EFI/debian/grub.cfg` we can boot anything that uses the Debian-signed GRUB binaries.

**Comment by adrian15** [comment]
It would be nice to take a look at the full grub.cfg.

In any case Tails is supposed to have a loopback.cfg file and a modified initrd so that it supports findiso or an equivalent parametre.

Otherwise I don't think I'm going to add custom code to try to be able to boot an specific iso like we might have done back in the day.

**Comment by mk-pmb** [comment]
Here's their full `grub.cfg`: [in GitLab](https://gitlab.tails.boum.org/tails/tails/-/blob/stable/config/binary_local-includes/EFI/debian/grub.cfg) / [plain text](https://gitlab.tails.boum.org/tails/tails/-/raw/stable/config/binary_local-includes/EFI/debian/grub.cfg)

**Comment by adrian15** [comment]
> Here's their full `grub.cfg`: [in GitLab](https://gitlab.tails.boum.org/tails/tails/-/blob/stable/config/binary_local-includes/EFI/debian/grub.cfg) / [plain text](https://gitlab.tails.boum.org/tails/tails/-/raw/stable/config/binary_local-includes/EFI/debian/grub.cfg)

Assuming they are still using Debian Live to build their isos you would have to convince them to use findiso and **add a loopback.cfg** file.

**Comment by mk-pmb** [comment]
> you would have to convince them

I was hoping we can find a general approach that works with all ISOs that use the Debian-signed GRUB binaries. I'll try if I can find a way to maybe chainload their EFI file or something.

**Comment by mk-pmb** [comment]
Seems like you were right and I was too optimistic.

<details><summary>What I tried (click to open)</summary>

I tried "Boot manually…" &rarr; "Bootable ISOs" but detected only my casper ISOs, not the tails ISO sitting directly next to them. So instead, I loopmounted it manually, and tried again:
* "Boot manually…" &rarr; "Operating Systems": `(isoloop)` didn't show up at all.
* "Boot manually…" &rarr; "Disks and Partitions (chainload)": `(isoloop)` and `(isoloop,msdos1)` are showing but both cannot be chainloaded in EFI mode. Not sure what the latter is.

So I opened a command-line and ran `chainloader (isoloop)/EFI/BOOT/BOOTX64.EFI`. For Windows EFIs, that's enough to boot into it, but for Tails, GRUB only says `/EndEntire`. So I ran `boot`, screen goes black, screen backlight becomes darker. I guess the tails EFI loader couldn't find its display drivers.

Next approach: `set root=isoloop` + `configfile /EFI/debian/grub.cfg`. This boots into a graphical progress bar that freezes at some point. When I press F2, it admits that it was unable to find the system partition, and after a little more waiting, drops into an initramfs shell. This is probably what you meant with "use findiso".

</details>

**Comment by adrian15** [comment]
## Well, basically when you normally boot a computer

- Load Linux Kernel into RAM with some parametres (among them the root filesystem UUID)
- Load Initrd into RAM
- Jump execution onto the Linux Kernel
- The Linux Kernel passes the root filesystem UUID to the Initrd which finds for it, mounts it, and then changes the system root (which for now was in the RAM) to the mounted filesystem.
- Boot continues.

## When you boot from a cdrom

The same thing happens but just changing that the initrd needs to seach into a cdrom with a given label or similar.

## When you boot from a usb

The same thing happens but just changing that the initrd needs to seach into a usb with a given label or similar.

## When you boot from an iso that it's inside a filesystem partition

- Load Linux Kernel into RAM with some parametres (among them the full path to the iso)
- Load Initrd into RAM
- Jump execution onto the Linux Kernel
- The Linux Kernel passes the *full path to the iso* to the Initrd which finds for its associated filesystem, mounts it, then loops-mount the iso, and then changes the system root (which for now was in the RAM) to the iso loop-mounted filesystem.
- Boot continues.

In this last step the way of saying the Initrd to do this search is done with *findiso* in some Initrd systems and with *fromiso* in some others.

A even nicer way of dealing with this is asking the distros to add a loopback.cfg file where they specify according to our specification how its system actually deals with this (findiso / fromiso). You can find a loopback.cfg example in Rescatux 0.74.
