### ISSUE TITLE
can detect windows not depending bootmgr or bcd？

### ISSUE THREAD

**Issue by adefadef** [supergrub/supergrub#15]
If I rename bootmgr and BCD file，supergrub not detect windows。NTboot（http://c-dl.qiniudn.com/dl/NTBOOT.rar  http://chenall.net/post/ntboot/ ) detect windows not depending bootmgr，but it doesn't support linux。

**Comment by adrian15** [comment]
@adefadef Which SG2D version are you using?
What would you use instead of bootmgr for detecting windows?

**Comment by adrian15** [comment]
There has not been any more feedback into this issue when the reporter was asked to provide feedback.

Hence we are closing this bug.
