### ISSUE TITLE
Display corrupted when start nano server with qemu via SuperGrub2Disk

### ISSUE THREAD

**Issue by Jimmy-Xu** [supergrub/supergrub#28]
I tried run windows nano server qcow2 with qemu (guest boot in UEFI mode)

--------------------------------------------------------------
# Method1: Boot from nano server qcow2 directly
sudo virt-install --connect qemu:///system \
    --name nanoserver --ram 2048 --vcpus=1 \
    `--disk path=/home/osboxes/iso/NanoGuestUEFI.qcow2,size=1,format=qcow2 \`
    --network=bridge=br0,model=virtio,mac=RANDOM \
    --graphics vnc,listen=0.0.0.0,port=5908 \
    --os-type=windows --os-variant=win8 `--boot uefi`

![](https://trello-attachments.s3.amazonaws.com/514ad8c7e51dbab31c000a8e/576152533ce66a35ad06807b/d9f5c030642eb1f738ab255de9547df3/nano-server-qcow2-direct.png)

--------------------------------------------------------------
# Method2: Boot from Super Grub2 Disk, then start nano server qcow2
sudo virt-install --connect qemu:///system \
    --name nanoserver --ram 2048 --vcpus=1 \
    `--disk device=cdrom,path=/home/osboxes/iso/super_grub2_disk_hybrid_2.02s6.iso \`
    `--disk path=/home/osboxes/iso/NanoGuestUEFI.qcow2,size=1,format=qcow2 \`
    --network=bridge=br0,model=virtio,mac=RANDOM \
    --graphics vnc,listen=0.0.0.0,port=5908 \
    --os-type=windows --os-variant=win8 `--boot uefi`

![](https://trello-attachments.s3.amazonaws.com/514ad8c7e51dbab31c000a8e/576152533ce66a35ad06807b/0cfc7ffcfa7605f8a2a05e252a9484ec/nano-server-qcow2-supergrub.png)

--------------------------------------------------------------
The problem is:  The display was corrupted after load OS nano server in method2.
How to fix it?

**Comment by adrian15** [comment]
1. Does the problem reproduce on latest Super Grub2 Disk versions which are now based on Grub 2.02 latest rcs?

Does it work properly if you try to efi-chainload it from an installed grub2?
Would you share with us its grub.cfg?

**Comment by adrian15** [comment]
Now that I take a second look at your screenshots.

Did you ever try to boot either:

- bootmgfw.efi
or
- bootmgr.efi

files?

Or is the 'Nano Server Recovery Console' supposed to only boot from that bootx64.efi file?

Anyways I wait for your feedback using latest Super Grub2 Disk version just in case upstream Grub has fixed these problems.

**Comment by adrian15** [comment]
There has not been any more feedback into this issue when the reporter was asked to provide feedback.

Hence we are closing this bug.
