### ISSUE TITLE
standalone efi can't work as well

### ISSUE THREAD

**Issue by cmtsij** [supergrub/supergrub#29]
I tried super_grub2_disk_standalone_x86_64_efi_2.02s9.EFI.
it can boot up to grub.
But grub can't find the grub.cfg and stay in command line mode.
the grub root is set as (memdisk)
folder tree in (memdisk):

boot/
&ensp;&ensp;&ensp;&ensp;grub/
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;local/
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;themes/
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;x86_64-efi/
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;fonts/

tmp/
&ensp;&ensp;&ensp;&ensp;tmp.txnBVOQCpe/boot/grub/
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;grub.cfg
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;adfmsg.cfg
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;unifont.pf2
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;loopback.cfg
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;sgd/
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;adf2012

I think some tmp files are fail to extract to /boot/grub.
So the grub can't find /boot/grub/grub.cfg

**Comment by cmtsij** [comment]
I confirmed super_grub2_disk_standalone_x86_64_efi_2.02s10b4.EFI works without any issue.
and super_grub2_disk_standalone_x86_64_efi_2.02s10b3.EFI has the same issue.
if you know the root cause, I think you can close this issue and the following release should be fixed.

**Comment by cmtsij** [comment]
I found the commit 532476946d723fb060071c2c4b20a4edb1ee3e11 has fixed this issue.
Sorry to bother you.
Thanks for this great software.

**Comment by adrian15** [comment]
Can you please try 2.02s10 beta 5 which has a different implementation of the fix of this problem ?

Does it work for you too?

Thank you for your feedback!

**Comment by cmtsij** [comment]
Yes, 2.02s10 beta 5 works as well.
Thank you.

**Comment by adrian15** [comment]
Standalone efi seems to work well on its own.
