### ISSUE TITLE
Installing i386-pc using grub-install.exe from grub-2.02~rc2-for-windows 

### ISSUE THREAD

**Issue by BoQsc** [supergrub/supergrub#31]
This issue is not with supergrub, actually supergrub works perfectly using Rufus, but it feels bloated.
So, I wanted to ask how did supergrub overcame these warnings and how they could be resolved with the original grub2 installer:

grub-install.exe can be downloaded from **grub-2.02~rc2-for-windows.zip** [ftp://alpha.gnu.org/gnu/grub/](url)

```
grub-install.exe  --boot-directory="F:\." --target="i386-pc" "\\?\F:" --force
Installing for i386-pc platform.
grub-install.exe: warning: File system `fat' doesn't support embedding.
grub-install.exe: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  Ho
wever, blocklists are UNRELIABLE and their use is discouraged..

```

**Comment by adrian15** [comment]
Check how we are now building usb images: https://github.com/supergrub/supergrub/blob/bae765815eb2a3c0c4758e88d87673debd26eeb9/supergrub-mkcommon#L246-L357 .

Basically you need to start your first partition 1 Mib after the start of the disk.
