### ISSUE TITLE
Is there a way to EFI-boot SGD w/o Primary Volume Descriptor?

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#38]
When I kill the Primary Volume Descriptor (replace `CD001` with `CD00x` to circumvent the annoying [gparted "enhancement" 771244](https://bugzilla.gnome.org/show_bug.cgi?id=771244)) of either 2.02s10 or 2.04s1, and then EFI-boot them on ia32, I get several `error: unknown file system` and then a GRUB rescue shell.
Is there a way to make GRUB use the GPT instead of PVD for searching its boot partition?

**Comment by adrian15** [comment]
I have no idea.
Super Grub2 Disk is built thanks to the grub-mkrescue command.
If you know how to build an image that does not use PVT then tell us the grub-mkrescue command line you use and we discuss if it's worth adding that extra image to SG2D.

You can also try to build your image manually thanks to the standalone efi images.
I guess that putting it as EFI/Boot/bootx64.efi file in a FAT32 filesystem in a GPT device should do it.

**Comment by adrian15** [comment]
These images are designed to be hybrid device-wise. That means that it boots as a cdrom and as a hard disk image too. That might explain your problem.

**Comment by mk-pmb** [comment]
Indeed. After I mutilate the PVD, there's no longer an ISO file system on the thumbdrive, so I'd expect SGD to boot in hard disk mode and use the GPT to detect whatever filesystems it was looking for. I'll see if I can find a hard disk only version, that would be more straigt forward than mutilating the hybrid.

**Comment by adrian15** [comment]
Yeah. Learn how to build a non ISO image with grub-mkrescue and then teach me. I might add it to the SG2D releases if it makes sense.

**Comment by adrian15** [comment]
@mk-pmb : Can you please subscribe to: https://github.com/supergrub/supergrub/issues/40 and gives us some advice there?

Thank you!

**Comment by adrian15** [comment]
Summary: No, there is not.
Closing the bug.
