### ISSUE TITLE
Advice on filenames for new usb images

### ISSUE THREAD

**Issue by adrian15** [supergrub/supergrub#40]
1]
1.1] Mostly done: An usb only version of Super Grub2 Disk with two partitions. The first one has 34 MB (not fully used) with the usual SG2D. The second one has 260 MB (empty) where you are supposed to put your loopback.cfg isos in /BOOTISOS/ .
* This disk can be boot from USB
* This disk cannot be boot from cdrom as SG2D hybrid versions usually do.
* This disk can boot in i386-pc (BIOS).
* This disk can boot in x86_64_efi.
* This disk can boot in ia32_efi.
* This disk does not support secureboot.

1.2] In the works:
* Same above plus secureboot support.
* Uses liveid to find its own device

2]
These would be the usual filenames:
```
super_grub2_disk_hybrid_2.04s2-beta2.iso
super_grub2_disk_i386_efi_2.04s2-beta2.iso
super_grub2_disk_i386_pc_2.04s2-beta2.iso
super_grub2_disk_standalone_i386_efi_2.04s2-beta2.EFI
super_grub2_disk_standalone_x86_64_efi_2.04s2-beta2.EFI
super_grub2_disk_x86_64_efi_2.04s2-beta2.iso
```

This is what I'm not sure about:

```
super_grub2_disk_XXXX_secureboot_YYYY_2.04s2-beta2.img
super_grub2_disk_ZZZZ_2.04s2-beta2.img
```

* Any idea?
* Should I use hybrid there ?
* Should I add usb ? Usbonly? Something about the isos?
* Should we rename the classic hybrid into bihybrid or something?

These new (secureboot and non-secureboot) usb disk images are hybrid platform-wise (i386-pc, i386-efi, x86_64-efi) but they are not hybrid device-wise (cdrom, usb, floppy) because they cannot boot neither from cdrom nor from floppy.

Examples are welcome.
Please also suggest about changing somehow old filenames.

Thank you!

**Comment by mk-pmb** [comment]
I'd prefer the version strings before the edition name, so that `sort` from GNU coreutils with `--version` mode will hopefully print a mostly chronological list. Also that would make it easier for me to delete old versions with just one rectangular selection. :-)

> Should I add usb ? Usbonly? Something about the isos?

Is it really that bent on USB? Won't it be able to boot from an internal harddisk? If I could boot it from a harddisk (and I hope so), maybe we can find a better name.

> hybrid platform-wise

Let's call that multiplatform.

**Comment by mk-pmb** [comment]
Actually, "multiarch" might be even better.

**Comment by mk-pmb** [comment]
Why is the EFI file name extension uppercase? If the basename supports lower (which shouldn't matter on FAT32 anyway), the extension can be as well.

**Comment by mk-pmb** [comment]
About the 2nd partition:
* Why 260 MB of emptiness? It's really large to keep around uncompressed, but too small to fit Ubuntu. How about we make it very small and people can resize it as they need?
* Which file systems can it be? (I'd like FAT32 and ext3 support.)

**Comment by adrian15** [comment]
> I'd prefer the version strings before the edition name, so that `sort` from GNU coreutils with `--version` mode will hopefully print a mostly chronological list. Also that would make it easier for me to delete old versions with just one rectangular selection. :-)

Don't think I'm going to change that bit but please give a concrete example of what you mean.

> > Should I add usb ? Usbonly? Something about the isos?
> 
> Is it really that bent on USB? Won't it be able to boot from an internal harddisk? If I could boot it from a harddisk (and I hope so), maybe we can find a better name.

Yeah, it could boot from an internal hard disk. But what is the point on wasting an internal hard disk and putting SG2D there? What is it your usecase? Maybe you can open a new issue as an RFE and we can discuss there.

> > hybrid platform-wise
> 
> Let's call that multiplatform.
> Edit 1: Actually, "multiarch" might be even better.
> Edit 2: Nope, sorry, I misread the examples as CPU architectures.

So we have:
* multiplatform
* multiarch
even if you are not sure about them it's good to have those new terms identified.

**Comment by adrian15** [comment]
> Why is the EFI file name extension uppercase? If the basename supports lower (which shouldn't matter on FAT32 anyway), the extension can be as well.

Either sourceforge did not let me upload lowercase efi files.
Or maybe I read somewhere that some UEFI firmwares only searched for uppercase EFI extensions.
Or maybe all of the disk examples that I found used the all capital letters filenames like /BOOT/BOOTX64.EFI and that's why I used that. The lowercase bit of super_grub2_disk... might have been left because that comes from a template but that can be fixed too... so that all the filename is uppercase like:

`SUPER_GRUB2_DISK_STANDALONE_I386_EFI_2.04S2-BETA2.EFI`


I'm not really sure on that one.

**Comment by adrian15** [comment]
> About the 2nd partition:
> 
> * Why 260 MB of emptiness? It's really large to keep around uncompressed, but too small to fit Ubuntu. How about we make it very small and people can resize it as they need?

Yeah, I had to fight with this one. Try to make a 250 MB partition and gparted is unable to resize it bigger. Make it 260 MB and gparted is able to resize it bigger. The final image would be probably compressed with zip so that you can only download around 30 MB (don't quote me on that size).

> * Which file systems can it be? (I'd like FAT32 and ext3 support.)
It should be a partition filesystem which secureboot grub implementations can read. So either FAT32 or ext3. It's going to be FAT32 because I want Windows users to be able to add their own ISOs.

But you should not worried about it. You can just remove that second partition and add your own ext3 or ext4 partition with the /BOOTISOS folder and add there and gather the same functionality. Or add whatever you want to.

The second partition is actually optional. If you ask me:

> why did you put it in the disk then? Why don't you put /BOOTISOS in the first partition instead?

The reason is that I don't want BIOS boot (i386-pc) to be broken while a final user uses gparted to make the first partition bigger and some grub important files are moved from block from 23 to 23+1 and then it no longer boots. Having a second partition for the iso files solves that problem nicely.

And it also avoids me having to explain how to setup an additional partition or... having to explain how to turn on the 'search on the same device as SGD' option when everything would be on the first partition.

**Comment by mk-pmb** [comment]
> > I'd prefer the version strings before the edition name,

> Don't think I'm going to change that bit but please give a concrete example of what you mean.

No problem. I'll just make a rename script

```sed
s~^((_?[^_]+){3})_(\S+)_([^_]+)(\.[a-z0-9]+)$~\L\1-v\4.\3\5\E~i
```

so the file names become

```text
super_grub2_disk-v2.04s2-beta2.hybrid.iso
super_grub2_disk-v2.04s2-beta2.i386_efi.iso
super_grub2_disk-v2.04s2-beta2.i386_pc.iso
super_grub2_disk-v2.04s2-beta2.standalone_i386_efi.efi
super_grub2_disk-v2.04s2-beta2.standalone_x86_64_efi.efi
super_grub2_disk-v2.04s2-beta2.x86_64_efi.iso
```

> But what is the point on wasting an internal hard disk and putting SG2D there?

#41

As for the EFI filename extension, I split that to #42.
It probably does not concern the release filename anyway because that one doesn't conform to `BOOT*.EFI` anyway.

> The second partition is actually optional.

Then I'd just not ship the 2nd partition, and instead tell people they can create an additional partition behind SGD if they like.

**Comment by adrian15** [comment]
I have finally implemented a new filenaming scheme.
Enjoy the new filenaming scheme at: https://www.supergrubdisk.org/2019/09/08/super-grub2-disk-2-04s2-beta2-downloads/ .
Thank you for your valuable feedback!

**Comment by mk-pmb** [comment]
Thanks for putting the version first! :-) What was your reasoning to write CD uppercase in `supergrub2-2.04s2-beta2-multiarch-CD.iso`?

**Comment by adrian15** [comment]
I have mostly borrowed syntax from Debian releases. Check e.g.: https://cdimage.debian.org/debian-cd/current/arm64/iso-cd/ .
