### ISSUE TITLE
Booting SGD from Harddisk

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#41]
From #40:

> Yeah, it could boot from an internal hard disk. But what is the point on wasting an internal hard disk and putting SG2D there? What is it your usecase? Maybe you can open a new issue as an RFE and we can discuss there.

My use case is to put a tiny, but very flexible boot helper onto the internal SSD of a netbook that needs most of its SSD space for Windows and whose BIOS-like config utility is very annoying. (I would never buy such a badly designed device, but this one I got for free. With a few restrictions, like Windows needs to stay there for rare occasions where the owner wants to use it.)

Using SGD, I only need to manage to get the BIOS-like config utility to accept the SGD EFI image once, and henceforth I will be able to boot whatever Linuxes will be on the internal hard drive. It will even save me the trouble of having to install Ubuntu's Grub onto that disk, because that again is made annoying by the bad config utility.

**Comment by adrian15** [comment]
You should be able to have a working Super Grub2 Disk on an EFI partition if you copy all of the contents from, let's say, https://sourceforge.net/projects/supergrub2/files/2.04s2-beta2/super_grub2_disk_2.04s2-beta2/supergrub2-2.04s2-beta2-x86_64_efi-CD.iso/download (but, be careful, without overwriting EFI/BOOT/BOOTX64.EFI) to the ESP/EFI partition.

You can rename the SG2D's BOOTX64.EFI to something else and register that file.

I'm not sure there's a need for an specific release image for your specific needs.

Maybe you don't know how to use the efibootmgr command (you can use from Rescatux live cd by the way).

**Comment by mk-pmb** [comment]
One of the problems with that BIOS-like config utility is that it resets the efibootmgr settings each time it fails to boot, so efibootmgr can't help me much. My plan is to use the boot settings inside the BIOS-like config utility to select SGD's EFI image as my preferred "Operating System" and then never touch it again.

**Comment by mk-pmb** [comment]
Thanks! I finally managed to find the `bootx64.efi`. Unfortunately, it did not have an ia32 companion. Is it specific to SGD even, or should it have worked with the existing `bootia32.efi` that I had left from my Ubuntu install attempt?

**Comment by mk-pmb** [comment]
Even with the `bootia32.efi` from the multiarch CD, I ony get a GRUB rescue shell. I'll try later whether it might be due to interference from the former (now empty) ESP on the secondary harddisk? Or maybe some other remains from Ubuntu's Grub that could confuse SGD?

**Comment by adrian15** [comment]
My proposal is that you copy the SG2D files into your internal hard disk EFI/ESP partition (having made a backup of the partition contents)... you are not supposed to have connected any SG2D disk.

It's your decision if you keep BOOTIA32.EFI from SG2D disk as-is or if you rename it. I recommend you to rename it so that, whatever you had as BOOTIA32.EFI is still there.

Try to use the multiarch USB files if the multiarch CD files do not work for you.

So... your internal ESP/EFI partition should have a /boot/grub/grub.cfg in there because that's what's inside the SG2D disk.

**Comment by adrian15** [comment]
For IA32 UEFI Firmware like yours there is an script called linuxium which tries to download and adapt IA32 grub binaries for your distribution. The script seems to me a mess. Too much complex. Anyways... I prefer to learn with you how you use SG2D to your use-case so that we can document it.

**Comment by mk-pmb** [comment]
Steps to reproduce:
1. Neuter the remains from my previous SG2D experiments: reformatted Gap0 as ext2, deleted the ISOIMAGE partition.
1. Backup the old ESP.
1. Format the ESP as FAT32, set flags boot+esp (no other flags).
1. Ensure no other partitions have the esp or boot flag set.
1. Download `supergrub2-2.04s2-beta2-multiarch-USB.img.zip`, extract, image-copy its first 64 MB onto a spare USB storage.
1. Start gparted, verify the 2nd partition is recognized as FAT, which means I had copied enough data. (About 34 MB would have been enough.)
1. Remove the 2nd partition. Mount the first one (`SG2DBOOT`).
1. Copy all the files from `SG2DBOOT` onto the ESP.
    * `boot/grub/grub.cfg` is one of them.
1. Reboot the tablet.
1. In the BIOS-like config utility, select `EFI/BOOT/BOOTIA32.EFI` as preferred OS. Save and exit.
1.  ```text
    Welcome to GRUB!

    error: no such partition.
    Entering rescue mode...
    grub rescue>
    ```
1. Remember you talked about block 23(+1) in #40.
1. Overwrite the entire ESP with zero-bytes (0x00 NUL).
1. Write `SG2DBOOT` partition image to the start of the ESP.
    * Do not (yet) resize the FAT FS to fit the partition size.
1. Reboot the tablet.
1. In the BIOS-like config utility, select `EFI/BOOT/BOOTIA32.EFI` as preferred OS. Save and exit.
1.  ```text
    Welcome to GRUB!

    error: no such partition.
    Entering rescue mode...
    grub rescue>
    ```

However, there's a tiny partition in front of my ESP. Is block 23 counted from the start of the partition, or from the start of the SSD? Which block size do you mean?

**Comment by mk-pmb** [comment]
To verify it could work at all, I booted the thumbdrive that I used to extract `SG2DBOOT`. It shows the SGD menu. I selected "Detect and show boot methods", it took almost forever, but then lists

```text
(hd1,gpt2)/efi/boot/grub.efi (hd1,gpt2)
(hd1,gpt2)/efi/boot/bootia32.efi (hd1,gpt2)
(hd1,gpt2)/efi/boot/bootx64.efi (hd1,gpt2)
(hd1,gpt2)/EFI/boot/grub.efi (hd1,gpt2)
(hd1,gpt2)/EFI/boot/bootia32.efi (hd1,gpt2)
(hd1,gpt2)/EFI/boot/bootx64.efi (hd1,gpt2)
```

I wonder why they are double? I selected `(hd1,gpt2)/efi/boot/bootia32.efi (hd1,gpt2)` and had the GRUB rescue shell again, same error as before, just in bigger font.

**Comment by adrian15** [comment]
> To verify it could work at all, I booted the thumbdrive that I used to extract `SG2DBOOT`. It shows the SGD menu. I selected "Detect and show boot methods"

Ok, so SG2D boots in your computer.

>, it took almost forever, but then lists
> 
> ```
> (hd1,gpt2)/efi/boot/grub.efi (hd1,gpt2)
> (hd1,gpt2)/efi/boot/bootia32.efi (hd1,gpt2)
> (hd1,gpt2)/efi/boot/bootx64.efi (hd1,gpt2)
> (hd1,gpt2)/EFI/boot/grub.efi (hd1,gpt2)
> (hd1,gpt2)/EFI/boot/bootia32.efi (hd1,gpt2)
> (hd1,gpt2)/EFI/boot/bootx64.efi (hd1,gpt2)
> ```
> 
> I wonder why they are double? I selected `(hd1,gpt2)/efi/boot/bootia32.efi (hd1,gpt2)` and had the GRUB rescue shell again, same error as before, just in bigger font.

They are double so that the files are found even if the capital letters do not match.

**Comment by adrian15** [comment]
> 12. Remember you talked about block 23(+1) in #40.

The block 23 was not a literal thing. And it only applies to BIOS based boot not to UEFI boot.

**Comment by adrian15** [comment]
> 16. In the BIOS-like config utility, select EFI/BOOT/BOOTIA32.EFI as preferred OS. Save and exit.
> Welcome to GRUB!
> 
> 17. error: no such partition.
> Entering rescue mode...
> grub rescue>

Can you check:

```
echo $prefix

ls

ls (With hard disk partition seen on prefix)
```

?

**Comment by mk-pmb** [comment]
```text
grub rescue> echo $prefix
Unknown command `echo'.
grub rescue> ls
(hd0) (hd1) (hd2)
grub rescue> ls (hd0)
(hd0) Filesystem is unknown.
grub rescue> ls hd0
error: no such partition.
grub rescue> ls (hd1)
(hd1) Filesystem is unknown.
grub rescue> ls hd1
error: no such partition.
grub rescue> ls (hd2)
(hd2) Filesystem is unknown.
grub rescue> ls hd2
error: no such partition.
```

Could it be that GRUB is missing a module to read GPT, because the USB edition uses MBR?

**Comment by mk-pmb** [comment]
I think that the GPT support is the problem. I tried this:

1. Created a new GPT on my thunbdrive with one partition 35 MB ext2.
1. Wrote the ESP partition from `supergrub2-2.04s2-beta2-multiarch-USB.img` onto the thumbdrive partition.
1. Set the "boot" and "esp" flag on that partition.
1. Boot the thumb drive in my netbook.
1. Same errors as when booting from SSD.

**Comment by adrian15** [comment]
This is an old issue.
Please reopen if needed.
