### ISSUE TITLE
Label the ESP

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#43]
Could you please set a file system label for the FAT partition, e.g. `SG2D_ESP`? That way I can mount it easier.
While you're at it, the partition names in the GPT could be more descriptive, too.

**Comment by adrian15** [comment]
> Could you please set a file system label for the FAT partition, e.g. SG2D_ESP? That way I can mount it easier.

Which filename are you referring to?
> While you're at it, the partition names in the GPT could be more descriptive, too.

Which filenames are you referring to?

Thank you.

**Comment by mk-pmb** [comment]
I meant `supergrub2-2.04s2-beta2-multiarch-cd.iso` for both.

**Comment by adrian15** [comment]
> Could you please set a file system label for the FAT partition, e.g. SG2D_ESP? That way I can mount it easier.
> While you're at it, the partition names in the GPT could be more descriptive, too.
> `supergrub2-2.04s2-beta2-multiarch-CD.iso` for both.

This image is done thanks to grub-mkrescue tool and thus I cannot modify how it's built. There is no option on its man page about those partitions labels.

**Comment by mk-pmb** [comment]
In that case, you could use sgdisk in an extra step after grub-mkrescue:

```text
$ sgdisk --print sgd_cd.iso | grep '^ '
   1              64             355   146.0 KiB   0700  Gap0
   2             356            6115   2.8 MiB     EF00  EFI boot partition
   3            6116           31087   12.2 MiB    AF00  HFSPLUS
   4           31088           31687   300.0 KiB   0700  Gap1
$ sgdisk \
  --change-name=1:supergrub_cd_gap0 \
  --change-name=2:supergrub_cd_esp \
  --change-name=3:supergrub_cd_hfsplus \
  --change-name=4:supergrub_cd_gap1 \
  -- sgd_cd.iso
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot.
The operation has completed successfully.
$ sgdisk --print sgd_cd.iso | grep '^ '
   1              64             355   146.0 KiB   0700  supergrub_cd_gap0
   2             356            6115   2.8 MiB     EF00  supergrub_cd_esp
   3            6116           31087   12.2 MiB    AF00  supergrub_cd_hfsplus
   4           31088           31687   300.0 KiB   0700  supergrub_cd_gap1
```

If you know more about what the gaps and hfs are meant to be, you can probably think of better names for them.

To set the FAT label:

```bash
# sudo apt-get install dosfstools
ISOLOOPDEV="$(sudo losetup --find --show --partscan sgd_cd.iso)"
sudo fatlabel "$ISOLOOPDEV"p2 SG2D_ESP
sudo losetup --detach "$ISOLOOPDEV"
```

Unfortunately, there seems to be no Ubuntu tool to set the label of an HFS+ partition. For now, the only way to change it, seems to be to binary patch it.

```bash
HFS_LABEL_OLD='ISOIMAGE        '    # pad the shorter one with spaces
HFS_LABEL_NEW='supergrub_cd_hfs'    # so they have equal length!
LANG=C sed -re 's~(\x01CD001\x01\x00 +)'"$HFS_LABEL_OLD"'( {4})~\1'"$HFS_LABEL_NEW"'\2~' -- orig.iso >labeled.iso
# You could use sed -i if it's ok to rename the file temporarily.
# Do NOT sed -i while it is mounted on a loop device.
```

__Caveats:__
* gparted will still show "ISOIMAGE" as the FS label.
* Also in `/dev/disk/by-label/` it will still show up as `ISOIMAGE`, even after detaching the loop device or replugging the thumb drive. However, the important part is, it will additionally show up as `supergrub_cd_hfs` here.

**Comment by adrian15** [comment]
Thank you for all the commands you have written here. One day they might be handy.

The supergrub2-2.04s2-beta2-multiarch-CD.iso is not supposed to be mounted by the final user.

Closing the issue.
