### ISSUE TITLE
Make a GPT edition of the USB image

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#45]
… so I can put multiple crypto partitions on the USB thumbdrive behind SGD, and refer to them by their partition name for decrypting. (There are no FS labels visible to the kernel, because the FS labels are part of the FS, thus hidden behind the encryption.)

aka I found an actual use case to justify this being a default feature. ;-)

**Comment by mk-pmb** [comment]
Today I found I need a `bios_boot` section for one of my computers. Please include that by default: Make a 1 MB (unformatted, ext2, anything) partition at the start of the disk, even before the ESP, and give it the `bios_boot` flag. Later when you install GRUB to the disk, it will automatically write a GRUB stub to that partition.

**Comment by adrian15** [comment]
> I might have suggested it on IRC already, but it bit me again today when I found I need a `bios_boot` section for one of my computers. Please include that by default: Make a 1 MB (unformatted, ext2, anything) partition at the start of the disk, even before the ESP, and give it the `bios_boot` flag. Later when you install GRUB to the disk, it will automatically write a GRUB stub to that partition.

The current offline implementation of usb gpt disk already includes that 1 MB bios_grub partition.
