### ISSUE TITLE
Show partition labels in addition to (hdX,gptX) also show my kernel

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#47]
After detecting boot methods, I'm now totally lost. It even lists kernels which I thought to have deleted, and it is missing some kernels that are stored on my ESP. But then the numbers don't make sense. Can you please write the partition's file system label in front of the right-side (hdX,gptX) in "Detect boot methods"?

Update: SGD was right, I had failed to deleted the old kernels. I fixed it, they are now gone for real. I can see these boot files in my ESP:

```text
EFI/BOOT/BOOTx86.EFI
EFI/supergrub/BOOTx86.EFI
grub/x86_64-efi/core.efi
grub/x86_64-efi/grub.efi
initrd.img-4.4.0-163-lowlatency
vmlinuz-4.4.0-163-lowlatency
```

but in `supergrub2-2.04s2-beta2-multiarch-USB.img` SGD's "Detect methods" only offers as "----- Operating Systems -----":

```text
(hd1,gpt3)/EFI/supergrub/BOOTx86.EFI (hd1,gpt3)
(hd1,gpt3)/EFI/boot/BOOTx86.EFI (hd1,gpt3)
(hd1,gpt3)/efi/supergrub/BOOTx86.EFI (hd1,gpt3)
(hd1,gpt3)/efi/boot/BOOTx86.EFI (hd1,gpt3)
```

(The "EFI required" warnings are gone because I booted in UEFI-only mode.)

How can I boot `4.4.0-163-lowlatency`?

Farther down there is "-- Entries from... (hd1,gpt3)/grub/grub.cfg --", I'd like the FS label here as well, instead of `...`. :-) I thought maybe it is that kernel, but it says

```text
error: no such device: XXXX-XXXX.             <-- UUID of my ESP
error: no such partition.
error: you need to load the kernel first.
```

Also I'd like more time to read that message. It took me several attempts until I tried editing the entry and adding a sleep command below. :-)

When I enter the grub command shell I can see with ls:

```text
(hd1,gpt4)/EFI/BOOT/BOOTx64.EFI
(hd1,gpt4)/EFI/BOOT/grubx64.efi
(hd1,gpt4)/casper/vmlinuz
```

That partition (hd1,gpt4) is ext3 and does not have the boot or esp flag, but still I'd like to see these in the operating systems menu, too.

Update: I found it in "-- Entries from... (hd1,gpt4)/grub/grub.cfg --" but it says

```text
error: file `/casper/vmlinuz' not found.
error: you need to load the kernel first.
```

**Comment by adrian15** [comment]
Please create a new issue for your specific kernel detection problem.

Thank you.

**Comment by adrian15** [comment]
If I'm not mistaken partition labels do not exist in MBR partition tables but only in GPT partition tables.
So that code would be conditional.
I'm not sure Grub supports reading GPT partition labels.
It would be nice if you could look it up.

Filesystem labels can be read with:
```
probe -s myvar -l (hd0,msdos1)
echo $myvar
```
If we add filesystem labels we need to add them not only to EFI entries but to everywhere.
Depending on the length they might make unreadable the kernel filename.

So it needs to be thought a lot how to implement this. I was even thinking of adding a dummy entry for the partition label before the kernel. But that's only if it has not already been shown.

Yes:
```
MYLABEL:
  (hd0,msdos1)/boot/vmlinuz-4.16.0
  (hd0,msdos1)/boot/vmlinuz-4.16.1
```
No:
```
MYLABEL:
  (hd0,msdos1)/boot/vmlinuz-4.16.0
MYLABEL:
  (hd0,msdos1)/boot/vmlinuz-4.16.1
```
Or maybe even...
```
MYLABEL (hd0,msdos1):
  (hd0,msdos1)/boot/vmlinuz-4.16.0
  (hd0,msdos1)/boot/vmlinuz-4.16.1
```


Maybe you could learn on how to build SG2D and make a pull request of it.

**Comment by mk-pmb** [comment]
> If I'm not mistaken partition labels do not exist in MBR partition tables but only in GPT partition tables.

That's correct. Actually I confused them. I'd rather see the filesystem label if there is one. If there is none or it's empty, the GPT partition label would be nice. however, it looks like GRUB can't do that. no big deal for me. all my disks with bootable stuff have good filesystem labels.


I think one label on top is enough, as the device name is repeated below in the path. In menus where the device name is not in the path, show it in addition to the label.

> Maybe you could learn on how to build SG2D and make a pull request of it.

It might take a few weeks to months though until I find the time. :-(

**Comment by adrian15** [comment]
I'm reviewing old issues.
Did you finally work on this or can I close this issue?

Thank you.

**Comment by mk-pmb** [comment]
Hi, thanks for reviewing the issues! Meanwhile I've started my own GRUB project and no longer rely on SGD. SGD still is a very nice project. Thanks for maintaining it, and for inspiring me to make my own!
