### ISSUE TITLE
Failed to find Intel® SSD Firmware Update Tool

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#50]
When I put [Intel's ISO](https://downloadcenter.intel.com/download/28749) next to rescatux in my boot-isos folder, `supergrub2-2.04s2-beta2-multiarch-USB.img` can only find rescatux.
Happened in one of my notebooks which was configured to boot in EFI mode only, and in carpediembaby's computer which apparently cannot (currently) boot in EFI mode, which is why we tried SGD in the first place.

**Comment by adrian15** [comment]
Super Grub2 Disk only supports to boot Linux distros from ISOs. Mostly with loopback.cfg support.
Unless you find a supported way of booting that iso from outside an iso... there's no going to be support for it.

Whatever kernel and initrd which uses that iso needs to be able to loop-mount the iso and boot from there. And that's not always the case.

**Comment by adrian15** [comment]
1) 
> In this case, can we show it with a warning "(not bootable by GRUB!) " in front of the entry?

Yeah, I might advertise loopback.cfg support there.

 2) This specific iso can be booted from SG2D but I'm not going to program it.
Current code can be found here: https://github.com/supergrub/supergrub/blob/41ed97fd1742b9435626a8bec4e60c9dda609d1e/menus/sgd/autoiso.cfg . Just in case you want to write a pull request ;) .

 3) You should try to ask Intel to add a loopback.cfg file to their iso as shown here: https://www.supergrubdisk.org/wiki/Loopback.cfg . I need to improve that page by the way (or just link it to a better explanation page).

**Comment by adrian15** [comment]
Intel SSD Firmware Update Tool was not detected because neither it's specifically supported not it has a loopback.cfg file.

Closing the issue.
