### ISSUE TITLE
menuentry - Grub2 boot - super_grub2_disk_hybrid_2.04s1.iso with grub2 isoboot

### ISSUE THREAD

**Issue by powersubergrub** [supergrub/supergrub#51]
Hello User,

did you can help to use super_grub2_disk_hybrid_2.04s1.iso with grub2 isoboot?

I have read with:
https://www.supergrubdisk.org/boot-super-grub2-disk-from-grub-cfg/

But it doesn't work.

My menuentry at this time:

```
menuentry "Super GRUB2 Disk" {
search --no-floppy --label boot --fs-uuid --set=root 23B2-C998
set isofile=/boot/iso/super_grub2_disk_hybrid_2.04s1.iso
loopback loop $isofile
configfile (loop)/boot/grub/loopback.cfg
}
```

23B2-C998 is my usb uuid.
My super_grub2_disk_hybrid_2.04s1.iso folder is /boot/iso/

Thank you.
power

**Comment by adrian15** [comment]
> But it doesn't work.

Can you please explain exactly what errors do you get?

**Comment by supergrubuser** [comment]
If i want to isoboot super_grub2_disk_hybrid_2.04s1.iso i get 
-->
 Press any key to continue ......
If i  press any key, i'm back to the Grub2 Entry Menue.

> bldkid -->
/dev/sdb1: LABEL="ISOBOOT" UUID="23B2-C998" TYPE="vfat" PARTUUID="c8602237-01"
 


`menuentry "Super GRUB2 Disk" {
search --no-floppy --label boot --fs-uuid --set=root 23B2-C998
set isofile=/boot/iso/super_grub2_disk_hybrid_2.04s1.iso
loopback loop $isofile
configfile (loop)/boot/iso/grub/loopback.cfg
}`

Thank you for your help.

**Comment by adrian15** [comment]
> If i want to isoboot super_grub2_disk_hybrid_2.04s1.iso i get
> Press any key to continue ......

Can you please press 'c' so that you go to the grub terminal and write (one line after another):

```
search --no-floppy --label boot --fs-uuid --set=root 23B2-C998
set isofile=/boot/iso/super_grub2_disk_hybrid_2.04s1.iso
loopback loop $isofile
configfile (loop)/boot/grub/loopback.cfg
```

This might give us more useful data about what it's happening.

**Comment by supergrubuser** [comment]
I have change the label ISOBOOT to MULTIBOTT
/dev/sdb1: LABEL="MULTIBOOT" UUID="23B2-C998" TYPE="vfat" PARTUUID="c8602237-01"

Than see with screensots:
https://imgur.com/a/LiC9Fdn

Thank you for more input.

**Comment by adrian15** [comment]
> Than see with screenshots:
> https://imgur.com/a/LiC9Fdn

Can you please write down the text you see in the screen so that it's useful for other people?

Thank you.

**Comment by supergrubuser** [comment]
The last Error Screen Message:

`You are loopback loopback booting in Super Gurb2 Disk
THIS IS NOT SUPPORTED
You are on your own.

Press escape to continue to looback bootet Super Gru2 Disk`

How can i solved the problem?

**Comment by adrian15** [comment]
> ```
> search --no-floppy --label MULTIBOOT --fs-uuid --set=root 23B2-C998
> set isofile=/boot/iso/super_grub2_disk_hybrid_2.04s1.iso
> loopback loop $isofile
> configfile (loop)/boot/grub/loopback.cfg
> ```
> 
> The last Error Screen Message:
> 
> ```
> You are loopback loopback booting in Super Grub2 Disk
> THIS IS NOT SUPPORTED
> You are on your own.
> 
> Press escape to continue to loopback bootet Super Gru2 Disk
> ```
> 
> How can i solved the problem?

Your problem is that it does not load Super Grub2 Disk but go back to the previous SG2D boot entry when you press ESC.

Can you please run from the grub> command line:

```
search --no-floppy --label MULTIBOOT --fs-uuid --set=root 23B2-C998
echo $root
echo $config_directory
```

?

I need to know the output of those two commands.
This might be a bug from the loopback.cfg support.

Thank you.

**Comment by supergrubuser** [comment]
https://imgur.com/a/hFrmgg7

```
search --no-floppy --label MULTIBOOT --fs-uuid --set=root 23B2-C998
echo $root
hd0,msdos1
echo $config_directory

```

**Comment by adrian15** [comment]
I see: https://github.com/supergrub/supergrub/blob/41ed97fd1742b9435626a8bec4e60c9dda609d1e/menus/loopback.cfg#L10 which it's:

```
source "(${root})/boot/grub/grub.cfg"
```
should be:
```
source "${config_directory}/grub.cfg"
```
instead.

And probably you should be using: sgdloop instead of loop as a variable so that it's unique enough. That would be an improvement on the documentation.

I might release a test iso for you to test later.

**Comment by supergrubuser** [comment]
Hello, if i change the supergrub/menus/loopback.cfg from my super_grub2_disk_hybrid_2.04s1.iso with isomaster i get another iso size.

http://littlesvr.ca/isomaster/

super_grub2_disk_hybrid_2.04s1.iso ---- 15,6 MB

super_grub2_disk_hybrid_2.04s1-change.iso ---- 12,7 MB

Which iso editor program did you use?

Greetz

supergrubuser

**Comment by supergrubuser** [comment]
beta beta
https://www.supergrubdisk.org/boot-super-grub2-disk-from-grub-cfg/
super_grub2_disk_hybrid_2.02s10-beta5.iso
beta beta

Why did this beta-iso works?
What did you have change in super_grub2_disk_hybrid_2.04s1.iso?

**Comment by supergrubuser** [comment]
Hello, no i have my own super_grub2_disk_hybrid_2.04s1-1.iso created.

loopback.cfg
```
clear
echo "You are loopback booting Super Grub2 Disk"
echo "THIS IS NOT SUPPORTED"
echo "You are on your own."
echo ""
echo ""
echo ""
echo $"Press escape to continue to loopback booted Super Grub2 Disk"
sleep --interruptible 9999
source "${config_directory}/grub.cfg"
```

**Comment by adrian15** [comment]
> Which iso editor program did you use?

We don't use any editor program. We either use grub-mkrescue or grub-mkimage to build the SG2D images.

**Comment by adrian15** [comment]
> Now my Super Grub Isoboot will work.

Nice. Thank you for testing the change.

**Comment by adrian15** [comment]
> When did think we get a official iso working Super_Grub2 with working isoboot?

I guess you mean working loopback cfg support from other grub instances.
I should release Rescatux first so I don't know.

**Comment by adrian15** [comment]
If you still have the same problem with the most recent versions of Super Grub2 Disk please open a new issue and refer back to this one.

Thank you!

Closing this issue.
