### ISSUE TITLE
Boot windows 10 install iso from /boot-isos

### ISSUE THREAD

**Issue by cagcoach** [supergrub/supergrub#52]
Heyho!
I'm trying to install the latest Windows 10 on my computer. For this I put the **Win10_1809Oct_v2_German_x64.iso** file into my /boot-isos folder just right next to the latest ubuntu1910.iso which already has been there. If I then select "Boot manually... > Bootable ISOs" it only shows the Ubuntu file. If I select "Detect and show boot methods", the same.
If I remove the Ubuntu iso, nothing will be shown.
Can someone replicate or explain this behavior? Is it a bug?

Greedings
Christian

**Comment by adrian15** [comment]
As I explained in https://github.com/supergrub/supergrub/issues/50

> Super Grub2 Disk only supports to boot Linux distros from ISOs. Mostly with loopback.cfg support.

Please ask Microsoft to add loopback.cfg support to their ISOs.

More info at: https://www.supergrubdisk.org/wiki/Loopback.cfg .
