### ISSUE TITLE
EFI files to be scanned always

### ISSUE THREAD

**Issue by adrian15** [supergrub/supergrub#55]
If EFI files are found in a partition then its kernel-initrd files are not found.

It makes sense because it's coded like that: https://github.com/supergrub/supergrub/blob/41ed97fd1742b9435626a8bec4e60c9dda609d1e/menus/sgd/osdetect.cfg#L444-L456 .

However that main logic was designed for the scenario when Windows was detected in a partition then it made no sense to search for Linux kernel in it. If you find efi files in a partition then it makes sense to search for kernel+initrd files too.

Whenever this is fixed you should get a kernel+initrd boot entries next to the EFI files boot entries.
These kernel+initrd boot entries are very useful because they would work even if you had deleted both the EFI and grub.cfg files (assuming you have not deleted the kernel and initrd images themselves).

Finally I think this should be rewritten so that EFI files are looked for in the first place and then all of the rest searching is done even if EFI files are found.

**Comment by CollaboratorGCM** [comment]
- Was this fixed? 
- If so, which version or beta operates to discover the linux+initrd combination presence in/on local drive?
Thanks

**Comment by adrian15** [comment]
Fixed on 2.06s2-dev35 branch or newer.
