### ISSUE TITLE
SuperGRUB2 Beta observations

### ISSUE THREAD

**Issue by CollaboratorGCM** [supergrub/supergrub#57]
I KNOW the SG2D author has provided comments on use of the IMG file on USB. In it he expresses that user(s) will probably need to expand the second partition. I wholeheartedly agree with the author.

Here is an observation that has been given me by someone I am collaborating with in the PUPPY Linux community that the SG2D author would understand, too.

> Currently there are a number of issues both with the SG2D implementation and the Puppy Grub2 setup.
> I don't think we are yet at the stage where a video/slideshow is possible. I need to get a better
> understanding of both and wish to experiment more. Some things also need clarification.
> 
> 1.
> Firstly I see the OOTB size of the 2nd partition as inadequate, so much so that it has to be expanded
> before any one of the 2/3 potential Puppy ISO candidates can be placed on it.
> In addition fat32 only allows for a save file (ext2 within) rather than a save folder which requires
> a Linux partition.
> In the last screenshot (Lets call that Experiment 1 )I sent, you will see in the PupSysinfo window that I had changed
> the expanded fat32 partition to f2fs. At the top right you will see that bionicpup64 has the original save file but that
> the scpup64 has a save folder.
> That first experiment confirmed that SG2D has no problem with f2fs detection.
> Whilst you know my personal preference is for the faster, kinder f2fs format I do not recommend it's use
> in this case as it entails deleting the 2nd partition and then creating an expanded f2fs partition with the same label
> before creating an identically named folder.
> We have to cater for people coming from Windows who are new to Linux. It has to be kept simple with no initial need
> to use GParted and plenty of space on the 2nd fat32 partition for a couple of typical ISOs plus adequate sized
> save files. (Typically 1GB to 2GB)
> What I propose therefore is to rework the SG2D image so that it fits on an 8GB (or greater) stick.
> 
> Experienced Linux users may elect to target a 16GB (or greater)stick & have the option to create a 3rd partition in
> a Linux format of their choice. That will give them the option of a save folder.

**Some of these observation could be useful understanding as SG2D goes from Beta to GA.**

**Comment by CollaboratorGCM** [comment]
I have been booting several ISOs via a SG2D burned to an CD. I have my ISOs on the PC's HDD in a folder /boot-isos. The booting SG2D has no problem finding the folder and the contents. 

Puppy LInux developers who generate their distro versions from the Puppy builder (ie. WOOFCE) are now creating distros which have a GRUB2 loopback.cfg such that SG2D can allow selection and boot. The community has been helpful and understanding how SG2D can benefit.

Was there any reason why the ISO version of SG2D does NOT have a "boot-isos" folder?

If it did AND it had an ISO contain within the CD's folder contents, say Rescatux; or one of the Puppy distros, say ScPup64 or LxScPup64 which are less than 300MB, **be found by SG2D at its startup from CD?** Is there something that prohibits the boot-isos folder contents discovery selected in SG2D option for finding bootables?

**Comment by adrian15** [comment]
> That first experiment confirmed that SG2D has no problem with f2fs detection.
> Whilst you know my personal preference is for the faster, kinder f2fs format I do not recommend it's use
> in this case as it entails deleting the 2nd partition and then creating an expanded f2fs partition with the same label
> before creating an identically named folder.
> We have to cater for people coming from Windows who are new to Linux. It has to be kept simple with no initial need
> to use GParted and plenty of space on the 2nd fat32 partition for a couple of typical ISOs plus adequate sized
> save files. (Typically 1GB to 2GB)
> What I propose therefore is to rework the SG2D image so that it fits on an 8GB (or greater) stick.

So we are talking about an alternative download to: supergrub2-2.04s2-beta2-multiarch-USB.img.zip which would have these modifications:
* Total size of image: 7,5 GB (so that it fits into a 8 GB USB disk)
* Second partition filesystem type is F2FS instead of FAT32
.

Yeah, that can be done. So a 3,5 GB image for a 4 GB USB disk is too small then?

Is there any special mkfs option required for that F2FS partition?

Can you please gather some more feedback from your community on the 4 GB USB versus 8 GB USB subject?

I don't mind having an additional IMG download for experts but I would prefer only to have one size of them.

**Comment by adrian15** [comment]
> Was there any reason why the ISO version of SG2D does NOT have a "boot-isos" folder in the files in the ISO?

You cannot edit ISOs after burning them to a cdrom or an usb. Why would I add a boot-isos folder in there?

> **Questions for running an SG2D that has ISOs on the SG2D CD**
> If it did AND it had an ISO contained within the CD's folder contents, say Rescatux; or one of the Puppy distros, say ScPup64 or LxScPup64 which are less than 300MB,
> 
>     * **would the ISO(s) be found by SG2D at its startup from CD?**
>     * Is there something that prohibits the boot-isos folder's contents to be discovered or  selected in SG2D for booting when all is contain on the single CD?

It would only be found if you turned on manually a flag (Extra GRUB2 functionality menu) that enables searching of isos inside the same SG2D device and probably also turning on the flag that searches on a cdrom too.

By default ISOs are not found in neither SG2D device, floppy disk or cdroms. Why? Because nobody would put ISOs on there.

**Comment by CollaboratorGCM** [comment]
This was asked because I "could" foresee someone having/making a self contained CD where all of the boot requirements, including boot-isos would be self contained in their CD.

I had not tried this, but am aware of the ISOmaster program's ability to generate a new tailoring of an ISO. 

**Another Idea, rather than an OOTB boot-iso on the main ISO session**
Further, if the CD/DVD is written as multi-session vs closed-session, there is an ability to add additional sessions to the CD/DVD. That "adding" could add a boot-isos folder with contents to the CD/DVD in accomplished by various programs in the Linux open-source community. Was curious if that, above, were done, if SG2D could/would find that folder on its CD/DVD and present its contents for boot selection?

Just curious if you knew of something that is either present or missing in SG2D.

Thank you for all the guidance you have given. 

**_BTW: Happy New Year_**

**Comment by CollaboratorGCM** [comment]
> Is there any special mkfs option required for that F2FS partition?

[**Found this**](http://manpages.ubuntu.com/manpages/cosmic/man8/mkfs.f2fs.8.html) 
And, **GParted** will f2fs format a partition as well.

**Comment by adrian15** [comment]
> This was asked because I "could" foresee someone having/making a self contained CD where all of the boot requirements, including boot-isos would be self contained in their CD.

If that happens they would use SG2D source code to build it. So they can modify whatever they need.

> I had not tried this, but am aware of the ISOmaster program's ability to generate a new tailoring of an ISO.

That's not true. That's not supported by me. I'm not aware of any program that keeps iso booting intact (and usb hybrid boot for that matter).

> **Another Idea, rather than an OOTB boot-iso on the main ISO session**
> Further, if the CD/DVD is written as multi-session vs closed-session, there is an ability to add additional sessions to the CD/DVD. That "adding" could add a boot-isos folder with contents to the CD/DVD in accomplished by various programs in the Linux open-source community. Was curious if that, above, were done, if SG2D could/would find that folder on its CD/DVD and present its contents for boot selection?
> 
> Just curious if you knew of something that is either present or missing in SG2D.

You have already been told on Puppy community that multi-session CDs are something of the past. I'm not going to invest time on this. If you know about how to add grub2 support for this and it works for you and you make a pull request I might accept it. Otherwise it will be kept on the sci-fi realm.

**Comment by adrian15** [comment]
> > Is there any special mkfs option required for that F2FS partition?
> 
> [**Found this**](http://manpages.ubuntu.com/manpages/cosmic/man8/mkfs.f2fs.8.html) . And, **GParted** will f2fs format a partition as well.

I know how to get the manpage for mkfs.f2fs.
My question is if an standard mkfs.f2fs execution is ok or if the puppy developers use some specific filesystems options for whatever the reason.

**Comment by adrian15** [comment]
Created: https://github.com/supergrub/supergrub/issues/61  (RFE: 8 GB size USB image with F2FS filesystem partition type).
We close this bug.

**Comment by CollaboratorGCM** [comment]
Hello, again. I know the thread has been closed, but hopeful SG2D can see this port.

The document we produced was a collaboration. You were/are an editor on that document in which it is there so you can see how we are attempting to show others your useful work.

I had posted earlier and also acknowledged your feedback and YOUR request. I now have received so comments that I am sharing with you. Merely FYI.

My collaborator writes:
"Looking at that post again RFE stands for "request for enhancement. Adrian appears to be waiting for answers to his questions: (See doubts below). (He has not produced a bespoke new image)

An alternative download to: supergrub2-2.04s2-beta2-multiarch-USB.img.zip which would have these modifications:

Total size of image: 7,5 GB (so that it fits into a 8 GB USB disk)
Second partition filesystem type is F2FS instead of FAT32
Doubts:

Adrian asks
o  A 3,5 GB image for a 4 GB USB disk is too small then?
o  Is there any special mkfs option required for that F2FS partition?
o  Has this been discussed enough on the Puppy community?
Waiting for useful @CollaboratorGCM feedback.


Here are some thoughts on those.
: A 3,5 GB image for a 4 GB USB disk is too small then?

Something must be done because as it stands the size of the 2nd partition is too small at 265MiB to fit in any one of  the current Puppy ISOs which range from 285MB to 408MB. In addition space is required for each Pup's save file or folder. When initially created
their contents are typically about 80MB but can quickly increase in size as packages are installed and may finish up at 700MB or more. It defeats the object of having a 2nd partition if only something as small as TCL could be placed there.

4GB is too small IMHO and 7.4GB would be a sweet spot. In my experience so called 8GB sticks are actually in the usable range of 7.4 to 7.8
Whilst a Linux format would suit us it would be invisible to Windows users which may be an issue for Adrian.

Having given it a lot of thought, I suggest that it is left at fat32 format. That is immediately suitable for Windows users and Puppy users with the proviso that Puppy users must use a save file. They will not get an option of a save folder until they convert
the partition to a Linux format.

An 7.4GB image might pose a compressed download size issue for Adrian so at a push a 3.7GB image would have to do. We then simply target an 8GB stick and then expand & optionally convert the 2nd partition.

: Is there any special mkfs option required for that F2FS partition?
No, but now suggest leaving it as fat32

: 
Has this been discussed enough on the Puppy community?
I think so but you may wish to give Adrian a link to our current unreleased draft web page"

Adrian you are an editor on our public document. If you choose feel free to add/change as you see fitting.

**Comment by adrian15** [comment]
You can find new related RFE issue at: https://github.com/supergrub/supergrub/issues/64 .
