### ISSUE TITLE
Show boot mode in main menu

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#58]
Hi! I want to see if I booted in EFI or legacy mode, so I'll run "Detect and show boot methods" and it will take some long time. Which inspired me: Can we show the boot mode right in that menu item?

Update: Patch in progress.

**Comment by adrian15** [comment]
https://github.com/supergrub/supergrub/blob/master/menus/sgd/tools.cfg#L34-L62

_with_platform_ function or _grub_platform_ variable might help you on coding what you are requesting.

**Comment by adrian15** [comment]
Anyways I think I was adding such a feature so that you know if you are in an specific SecureBoot Distro-Grub, UEFI or BIOS mode.

But, go ahead, I might reuse your work in another way.

**Comment by mk-pmb** [comment]
I chose the "Boot manually" entry instead because it had more space.

**Comment by adrian15** [comment]
I will add a new entry labeled *Detected boot mode* that will use a similar code to yours.

Thank you!

**Comment by adrian15** [comment]
Fixed on 2.06s2-dev35 branch or newer.

**Comment by mk-pmb** [comment]
What is that `$"text"` syntax? I've never seen that in GRUB. (I know `$'text'` from bash but that doesn't work with double quotes.)

**Comment by adrian15** [comment]
> What is that `$"text"` syntax? I've never seen that in GRUB. (I know `$'text'` from bash but that doesn't work with double quotes.)

Well, as you can see in our [TRANSLATION page](https://github.com/supergrub/supergrub/blob/2.06s3-beta3/TRANSLATION.md#for-developers) it means that a given text will be used for translation.

If you don't have that dollar sign at the start it does not get translated.

I have taken a look at the latest [GRUB2 manual](https://www.gnu.org/software/grub/manual/grub/grub.html) and I don't see any example of that.

So I'm not sure if it's something that it's documented elsewhere or if it's an specific SG2D feature that it's handled in another script like the most probable one: [update_po](https://github.com/supergrub/supergrub/blob/2.06s3-beta3/update_po) which uses `xgettext` command.

**Comment by mk-pmb** [comment]
Thanks!
