### ISSUE TITLE
SuperGRUB2 to upgrade a WinPC

### ISSUE THREAD

**Issue by CollaboratorGCM** [supergrub/supergrub#59]
I am curious to see if SG2D can be used to upgrade a Win machine?

I have the Win Upgrade ISO downloaded from here

It is in my collection of ISO folders on my PC; namely /boot-isos on sda3 (NTFS). SG2D finds all of my ISOs (loopback.cfg) and they boot fine.

**But I am unsure how** to use SG2D to boot the Win upgrade ISO that is there.

I found this and am wonder how this could be implemented in SG2D to boot the ISO. 
```
menuentry "SG2D Boot Win-Upgrade" {
  search -f "--set-root /boot-isos/MS-WinUpgrade.iso"
  insmod ntfs
  insmod ntldr
  insmod part_msdos
  insmod memdisk
  linux16 /boot-isos/memdisk iso
  initrd16 /boot-isos/MS-WinUpgrade.iso
}
```
Not sure if there is a way to do this via SG2D. Any ideas/corrections on how to use that in SG2D to accomplish booting the ISOHELP, please.

**Comment by adrian15** [comment]
Using memdisk from syslinux project is not supported and it probably only works in BIOS systems.
Please write Microsoft so that their isos support loopback.cfg.
