### ISSUE TITLE
RFE: 8 GB size USB image with F2FS filesystem partition type

### ISSUE THREAD

**Issue by adrian15** [supergrub/supergrub#61]
An alternative download to: supergrub2-2.04s2-beta2-multiarch-USB.img.zip which would have these modifications:

-     Total size of image: 7,5 GB (so that it fits into a 8 GB USB disk)
-     Second partition filesystem type is F2FS instead of FAT32

Doubts:

- A 3,5 GB image for a 4 GB USB disk is too small then?
- Is there any special mkfs option required for that F2FS partition?
- Has this been discussed enough on the Puppy community?

Waiting for useful @CollaboratorGCM feedback.

**Comment by CollaboratorGCM** [comment]
Expect that your questions will be answered.

**Comment by adrian15** [comment]
Closing as per https://github.com/supergrub/supergrub/issues/57 update.
