### ISSUE TITLE
Pad our menu files to make them more hex-editing friendly

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#62]
My first hour of trying to implement #58 was trying to figure out how to revive my SGD thumbdrives with least damage, because I don't have a spare one around atm. Looks like I'll have to rewrite at least one of them, so to increase my chances of that rewrite being the last one in a while, it seems a good idea to me to pad a lot of our config files more, with patterns easily found by sed, so I can easier inject my changed code with a hex disk editor. :-) What do you think?
We might have discussed this some time ago already but I can't find it anymore.

**Comment by adrian15** [comment]
This is a very rare use-case.
Although it's quite interesting from a technical standpoint I am afraid I will close the issue.
