### ISSUE TITLE
Puppy Linux's FATDOG Distro is announced on DistroWatch

### ISSUE THREAD

**Issue by CollaboratorGCM** [supergrub/supergrub#65]
FATDOG indicates SuperGrub2Disc as a method to boot. **[See the forum announcement here.](http://murga-linux.com/puppy/viewtopic.php?p=1044042#1044042)** under 'New Features'.

You may want to validate or acknowledge

**Comment by adrian15** [comment]
This is not an issue.
This is not a forum. Please do not bring similar issues.

Closing the issue.
