### ISSUE TITLE
SG2D and GRUB Customizer tool

### ISSUE THREAD

**Issue by CollaboratorGCM** [supergrub/supergrub#66]
Can this be used to generate a proper GRUB for SG2D boot discovery? ... loopback.cfg

[GRUB Customizer tool](https://www.dedoimedo.com/computers/grub-customizer.html)

**Comment by adrian15** [comment]
> Can this be used to generate a proper GRUB for SG2D boot discovery? ... loopback.cfg
> 
> [GRUB Customizer tool](https://www.dedoimedo.com/computers/grub-customizer.html)

Can you please describe more in detail what the GRUB Customizer tool is supposed to do according to you?

Thank you.

**Comment by CollaboratorGCM** [comment]
Its an interesting Linux utility that attempts to make it "**friendlier**" to get the GRUB2 boot-loader set up correctly.

**Comment by adrian15** [comment]
In the thread you linked to it seems that ISOs seem to work for you.
Closing the issue.
