### ISSUE TITLE
Include SGD's GRUB config when detecting GRUB configs

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#71]
Hi! When I "boot manually" by searching for GRUB config files, it seems SGD skips the one it booted itself from. Could you include it in the list, prefixed with `(current SuperGrub) `? That way I could
* easily see SGD's disk number, useful when detecting all boot methods.
* be assured the (other) GRUB config I select is not on the SGD disk.

**Comment by adrian15** [comment]
This is made on purpose so the multiple partitions on the hybrid SG2D did not confuse users.

On the extra functionality menu you can find an option to turn on the search inside SuperGrub device.
Not sure what the name was for that.

**Comment by mk-pmb** [comment]
I see. I didn't know this also applies to config search. With sdgsearch=on, it finds itself. :-)

**Comment by mk-pmb** [comment]
Thanks. I was about to clean it up myself but you were quicker. :-)
