### ISSUE TITLE
Tablet screen thinks it's tall and portrait

### ISSUE THREAD

**Issue by mk-pmb** [supergrub/supergrub#73]
Hi! In my new tablet, the screen thinks it's tall and positioned portrait, even when I have it in dock and thus the screen is positioned landscape. As a result, the GRUB menu [shows sideways and stretched](http://l.proggr.de/?204o7szzh). I'm currently on `#grub`, trying to debug it with Jordan_U's help.
Update: `videotest 600x800` looks good. In [videoinfo](https://www.gnu.org/software/grub/manual/grub/html_node/videoinfo.html), that would be `0x006  600 x  800 x 32 (2400) …` on adapter `EFI GOP driver`. I'm now trying to figure out how to configure that.

**Comment by mk-pmb** [comment]
Let's offer a new option in the "Extra GRUB2 functionality" menu to select some common screen resolutions (at least 640x480 and 800x600), their swapped twins (480x640, 600x800), and a hint that you can edit the menu command to put your custom values. I'll try and make a PR for that.

**Comment by adrian15** [comment]
Ok, seems a nice addition to have.
PRs are welcomed.

Thank you.

**Comment by mk-pmb** [comment]
It will be weeks to months until I'll have time for this research, so if anyone can do it earlier, feel free to go ahead.

**Comment by adrian15** [comment]
I could work on that functionality if you could give me the commands for both BIOS boot and UEFI boot so that the user can change their screen resolutions seamlessly.

You have mentioned both videotest and videoinfo but I have no idea if they can be used in both BIOS boot mode and UEFI boot mode.

**Comment by mk-pmb** [comment]
Unfortunately I don't have my research notes anymore, and the device that had the portrait screen problem no longer works, so I can't test it anymore.

**Comment by adrian15** [comment]
There's no point on keeping this issue open if there's no one being able to test this in an actual device and providing code.
