### ISSUE TITLE
Is a partition formatted as BTRFS on a gpt disk acceptable for containing ISOs

### ISSUE THREAD

**Issue by CollaboratorGCM** [supergrub/supergrub#76]
Will SG2D find isos in /BOOTISOS on a GPT disk where its partition is formatted as BTRFS?
And if so, which of the several SG2D downloads do you recommend that would have the support needed?

Thanks in advance

**Comment by CollaboratorGCM** [comment]
Bump

**Comment by adrian15** [comment]
I am not sure because BTRFS does not use partitions but something else (similar to snapshots).

You should test it and give us feedback about it.

**Comment by adrian15** [comment]
There has not been any more feedback into this issue when the reporter was asked to provide feedback.

Hence we are closing this bug.
