### ISSUE TITLE
Super Grub2 Error

### ISSUE THREAD

**Issue by Johncooool** [supergrub/supergrub#77]
I am facing an issue with Grub2 when using UEFI.

It is working well on legacy support but I need it to work on UEFI.
I only need it on USB to boot WIndows 8.1.

I only have one O/S installed. Only Win8.1

I does not load into the Grub menu.

I tried many versions of Super Grub2 -EFI and all gave the same error.

I get the “Welcome to Grub!”

Then repeated message error: Unknown filesystem

The it goes to rescue mode.

I tried ls with all the partitions and nothing happened.

How can I fix it?

**Comment by adrian15** [comment]
You need to mention exactly which version of SG2D you are using.
And how you are putting it into your USB/CDROM in order to get meaningful help.

As this is an old issue I will close it but don't hesitate to reopen it again or open a new issue.

Thank you.
