### ISSUE TITLE
SG2D mentioned as a boot-tool

### ISSUE THREAD

**Issue by CollaboratorGCM** [supergrub/supergrub#78]
Use of SG2D is mentioned on distrowatch, **[here](https://distrowatch.com/?newsid=11125)**

The Puppy Linux community has supported your utility thruout 2020. Show some love via **[their GIT website](https://github.com/puppylinux-woof-CE/woof-CE/tree/testing/woof-distro)**.

**Comment by adrian15** [comment]
This is not an issue.
We therefore close it.
