### ISSUE TITLE
Has the Multi-image SG2D combined IMG-ZIP disappeared?

### ISSUE THREAD

**Issue by CollaboratorGCM** [supergrub/supergrub#84]
Adrian provided this Jan,2020. BUT ...
Cannot find on GIT **or** on the main announcement page.

Anyone have a source?

**Comment by adrian15** [comment]
> Adrian provided this Jan,2020. BUT ... Cannot find on GIT **or** on the main announcement page.
> 
> Anyone have a source?

What do you mean exactly?

Once you enter [https://sourceforge.net/projects/supergrub2/files/](https://sourceforge.net/projects/supergrub2/files/) you can enter into any of the versions/directories and you have a zip (E.g. [https://sourceforge.net/projects/supergrub2/files/2.06s1-beta2/super_grub2_disk_2.06s1-beta2.zip/download](https://sourceforge.net/projects/supergrub2/files/2.06s1-beta2/super_grub2_disk_2.06s1-beta2.zip/download) ) which has all of the release on it.
