### ISSUE TITLE
Detect default font on more paths

### ISSUE THREAD

**Issue by petsam** [supergrub/supergrub#87]
With deep respect to your excellent work, I would like to ask you to consider some small proposed changes, if you agree  and there is no other reason that may conflict. I would have done a merge request, if I wasn't so unfamiliar with git :sob: .

I am currently working on a way to include sg2d grub menus as an addon utility to a standard grub (automatic) configuration. If/when I confirm it is working well, I will request/send a PKGBUILD to AUR.

During this work, I have found some small things that might or should be changed, in order for this to work better (or at all) in Arch-based systems.

For the time, I do some of those modifications with PKGBUILD provided ways using sed, or adding extra file(s). If you are interested in this, I may have some ideas :wink: .

* main.cfg
1. Setting sg2d_directory var (this gave me the more trouble...)
Since `export sg2d_directory` sets the base dir var in the main.cfg, no other re-set and export should be required, or needed. The value of the var survives during all other menus `configfile` are passed into. I did not find any other place that actually changes this path for a reason, but I maybe wrong.
2. Font is pinned/hardcoded to a non-standard path (to my knowledge, from Arch `grub` package). Arch (and Mint) are known to use `$prefix/fonts/` folder. Maybe this comes from other distributions?
```
loadfont "$prefix/unifont.pf2"
```
to 
```
if [ -s "$prefix/fonts/unicode.pf2" ]
    loadfont "$prefix/fonts/unicode.pf2"
elif [ -s "$prefix/unicode.pf2" ]
    loadfont "$prefix/unicode.pf2"
elif [ -s "$prefix/unifont.pf2" ]
    loadfont "$prefix/unifont.pf2"
fi
```

3. "$prefix" path, although it is used in the explanation text, is not used in the following code, in favor of a pinned path. It is required for consistency (and control from "others"), but is **needed** for btrfs subvolumes with "/@/" root prefix.
```
elif [ -e "/boot/grub/sgd_custom.cfg" ]; then
  source /boot/grub/sgd_custom.cfg
```
to
```
elif [ -e "$prefix/sgd_custom.cfg" ]; then
  source $prefix/sgd_custom.cfg
```
* afd2012.cfg

As described for main.cfg, 
```
set sg2d_directory="${config_directory}/sgd"
export sg2d_directory
```
has to be removed/deleted. 

As explained in Grub2 Manual, each time using `configfile`, $config_directory changes to the current/new file directory. This does not happen with `source`.

**Comment by mk-pmb** [comment]
Thanks for pointing these out. It seems this project has fallen into hibernation, but I'm planning on rebooting it in another name, and those ideas will be important then.

**Comment by petsam** [comment]
> I'm planning on rebooting it in another name, and those ideas will be important then.

I would be glad to help/contribute. I have some Archlinux and grub2 experience and also interested in such a project.

Tag me if and when you want, even for some ideas and sharing experience :wink:

**Comment by adrian15** [comment]
>2. Font is pinned/hardcoded to a non-standard path (to my knowledge, from Arch `grub` package). Arch (and Mint) are known to use `$prefix/fonts/` folder. Maybe this comes from other distributions?
> ```
> loadfont "$prefix/unifont.pf2"
> ```
> 
> to
> 
> ```
> if [ -s "$prefix/fonts/unicode.pf2" ]
>     loadfont "$prefix/fonts/unicode.pf2"
> elif [ -s "$prefix/unicode.pf2" ]
>     loadfont "$prefix/unicode.pf2"
> elif [ -s "$prefix/unifont.pf2" ]
>     loadfont "$prefix/unifont.pf2"
> fi
> ```

We should not make Super Grub2 Disk slower because of these changes so this should be like this instead:

```
loadfont "$prefix/unifont.pf2"
```
to 
```
if [ -s "$prefix/unifont.pf2" ]
    loadfont "$prefix/unifont.pf2"
elif [ -s "$prefix/fonts/unicode.pf2" ]
    loadfont "$prefix/fonts/unicode.pf2"
elif [ -s "$prefix/unicode.pf2" ]
    loadfont "$prefix/unicode.pf2"
fi
```

Later on we can study if we should use another path with it is more standard. I think this was done by @jordanu and I'm not sure what was his rationale for this specific path.

**Comment by adrian15** [comment]
Please create specific issues for 1 and 3 so that I can focus and reply to them there.

This issue will be about the fonts issue.

**Comment by adrian15** [comment]
As I am checking: https://github.com/supergrub/supergrub/pull/68 in depth I think that this issue might be fixed when that pull request is adapted slightly and merged.

**Comment by adrian15** [comment]
This commit: https://github.com/supergrub/supergrub/commit/c36ecd0ed62faf0e05bc2250f7c2df4674213319 when it lands in main branch... should be fixing part of this issue.

This is why I'm closing the issue right now.

Whenever 2.06s4-beta1 appears as an official download you can revisit the 1 and 3 points that you described here. If they are still a problem please open a new issues related to them so that we can fix them.

Thank you very much!
