### ISSUE TITLE
UEFI boot of SuperGrub2

### ISSUE THREAD

**Issue by ggustaf** [supergrub/supergrub#89]
Development::

**Please offer a Linux install program for spinning disk or SSD which can boot SG2D directly from UEFI firmware.** 

**Idea**: The largest Linux user base consists of novices who struggle to make a USB stick, then download (https://www.supergrubdisk.org/) has no option for them.  An install to local disk enables start of SG2D without locating and booting a USB drive. The boot is from a modern firmware menu (e.g., keys F8, F11 ). 

**Example**:  Archive disks /dev/sdb, /dev/sdc which contain EFI partitions and Ext 4 partitions for multiple versions of Linux Mint or Ubuntu.  The service of SG2BD is to enable boot of any Ext 4 partition without using not-for-novices grub recovery (which is all novices are likely to see).

Adrian Lopez, Jordan Uggla, Marcel Krause: 
**Listen to the applause from the cheap seats high in the stadium. Well done!**

-Grant Gustafson, Univ Utah Math

**Comment by adrian15** [comment]
That Super Grub2 Disk internal disk installation would not work as expected if you delete the EFI partition.

However if you have already put Super Grub2 Disk into an USB disk thanks to Balena Etcher (or a similar tool) you can boot from there.

I am not sure many people would install Super Grub2 Disk in their systems either. It's usual a recovery tool.

I am willing to listen other potential users here asking for such an installation script.

Currently, if I'm not mistaken you can just drop the standalone EFI image into your EFI partition and many UEFI firmwares might detect it and allow you to boot from it even if you don't register it explicitly as a UEFI boot entry.
