### ISSUE TITLE
update to include grub 2.06

### ISSUE THREAD

**Issue by Randall-Glass** [supergrub/supergrub#90]
All versions below grub 2.06 is subject to BootHole vulnerability malware security problem.

\https://www.bleepingcomputer.com/news/security/grub2-boot-loader-reveals-multiple-high-severity-vulnerabilities/

So please update Rescatux to use grub 2.06

**Comment by adrian15** [comment]
I will working on the next months on bringing up a Super Grub2 Disk based on Grub 2.06.
