### ISSUE TITLE
Provide pre-build ARM images

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [supergrub/supergrub#91]
There is an increasing number of general-purpose ARM devices capable of running Grub compatible OSes and booting via UEFI. I'm seriously missing pre-build Super Grub 2 disk images for armhf, armel and aarch64.

Of course, armhf and armel might be useful, but I think aarch64 images would be sufficient. I don't know of any general purpose UEFI 32 bit ARM device.

**Comment by adrian15** [comment]
There has not been any more feedback into this issue when the reporter was asked to provide feedback.

Hence we are closing this bug.
