### ISSUE TITLE
stable non-UEFI IMGs?

### ISSUE THREAD

**Issue by dchmelik** [supergrub/supergrub#94]
Will there be Super Grub 2 stable non-UEFI IMGs?  Like a fair number of people about my age, I will never use UEFI until absolutely unavoidable but of course my 64-bit (even some 32-bit) PCs have USB--more convenient than optical disc (ODs) if works but sometimes stables work and betas don't.  PC shop owners told me in 2010s ODs are dead which even schools in '0s phased out; there may be more demand for IMGs than ISOs, which often don't work for USB...

**Comment by adrian15** [comment]
These are the latest stable downloads: https://www.supergrubdisk.org/2019/08/26/super-grub2-disk-2-04s1-downloads/ .

Under: *CD/USB/HD BOOTABLE IMAGES* and *Old BIOS (non UEFI) systems only.* sections you can find: [Download super_grub2_disk_i386_pc_2.04s1.iso](https://sourceforge.net/projects/supergrub2/files/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_i386_pc_2.04s1.iso/download).

That's what you are asking for. It's already there.

Unless I have misunderstood your question, of course.

**Comment by dchmelik** [comment]
I guess they're ISOs that work as USB IMGs.  That one only has i386 name but beside says 'i386 and x86_64'...

**Comment by adrian15** [comment]
> I guess they're ISOs that work as USB IMGs.

Yes, they are hybrid images. You should use Balena Etcher to write it into the USB properly, be warned the USB contents will be erased.

> That one only has i386 name but beside says 'i386 and x86_64'.

Yes, x86_64 systems are retro-compatible with i386. That means that you can run i386 code in an x86_64.
And I think that every system that it's setup as BIOS (not as UEFI) works that way... expecting an i386 at the very stages of boot.

Additionally I think that if you run i386 Grub then you can load 64bit Linux kernels without a problem (not 100% sure on this).
