### ISSUE TITLE
ISO Boot SuperGrub2-XY.iso  or Install & boot SuperGrub2 from HardDrive Partition

### ISSUE THREAD

**Issue by RYRNRY** [supergrub/supergrub#97]
I have a laptop which is less than 10 years old.  I would like to setup GRUB2 to directly boot SuperGrub2-XY.iso

Is it possible to install SuperGrub2 onto HardDrive Partition and add grub2 entry to boot from there ?

```
----------------------------------------------
**CURRENT PARTITION TABLE**
----------------------------------------------
/dev/sda1 : EFI   System Partition
...
/dev/sda3 : Windows Boot Partition
/dev/sda4 : Windows 10 O/S
/dev/sda5 : Ubuntu 20.03 - Main GRUB2 loader to boot all other Linux variants
...
/dev/sda8 : ISO files storage
----------------------------------------------
```

**File : (sda5):/boot/grub/grub.cfg**

Grub Menu entry to boot from SuperGrub2-XY.iso
```

#------------------------------------------------
menuentry 'ISO Boot SuperGrub2' {
  set root=(hd0,gpt8)
  set if=/iso_files/super_grub2_disk_hybrid_2.04s1.iso
  loopback loop $if
  configfile (loop)/grub/loopback.cfg
}
#------------------------------------------------

```
**Boot behavior**

1. super_grub2_disk_hybrid_2.04s1.iso burned on a USB drive using Rufus (https://fufus.ie)
  - can boot successfully 

2. Boot from Grub2 Menu Entry - 'ISO Boot SuperGrub2'
  - Message "Press any key to continue..." is displayed and reverts back to main menu

3. Manual Boot from GRUB Command line

```
  grub> set root=hd0,gpt8
  grub> set if=/iso_files/super_grub2_disk_hybrid_2.04s1.iso
  grub> ls ($root)/$if
		super_grub2_disk_hybrid_2.04s1.iso
  grub> echo $config_directory
        (hd0,gpt1)/EFI/ubuntu
  grub> loopback loop $if
  grub> configfile (loop)/boot/grub/loopback.cfg
        You are loopback booting Super Grub2 Disk  
        THIS IS NOT SUPPORTED
	    You are on your own.
	   
	    Press escape to continue to loopback booted Super Grub2 Disk
```
		
4. Beta ISO supergrub2-2.06s1-beta2-multiarch-CD.iso 
  - Same behavior as above

5. Created SuperGrub2-RY.iso from super_grub2_disk_hybrid_2.04s1.iso 
   by updating (ISO))/boot/grub/loopback.cfg 
   replaced last line 
   `source "${root}/boot/grub/loopback.cfg"`
   to
   `source "${config_directory}/grub.cfg"`

   Booting from modified ISO results in exactly the same behavior as above.

**Comment by adrian15** [comment]
> You are loopback booting Super Grub2 Disk
> THIS IS NOT SUPPORTED
> You are on your own.
> 
>     Press escape to continue to loopback booted Super Grub2 Disk

Once you press ESC there you get to the Super Grub2 Disk menu.
Isn't this what you want?

**Comment by adrian15** [comment]
Alternatively you can do something similar to:

```
mkdir /mnt/sgd
mount -t auto -o loop /path/to/sgd.iso /mnt/sgd
mkdir /boot/sgd
cp -a /mnt/sgd/boot/sgd/* /boot/sgd/*
cp -a /mnt/sgd/boot/grub/grub.cfg /boot/sgd-launcher.cfg
```

Then your default grub.cfg can have an entry similar to:
```
configfile /boot/sgd-launcher.cfg
```
to invoke Super Grub2 Disk.

Note: It's probably easier to get the files from github itself ( https://github.com/supergrub/supergrub/archive/refs/heads/master.zip ) rather than mounting them from the iso... or maybe mounting the usb version of SG2D.

Hopefully you get the idea and you can post the exact commands that worked for you.

**Comment by adrian15** [comment]
There has not been any more feedback into this issue when the reporter was asked to provide feedback.

Hence we are closing this bug.
