### ISSUE TITLE
Support: Possible to re-sign secureboot and then chain boot other ISOs?

### ISSUE THREAD

**Issue by gcb** [supergrub/supergrub#98]
I have some systems with windows secureboot keys and others with custom key.

So the first question is if i can simply sign the EFI file with the custom key too?

Then does the grub2 boot process, after booting into secureboot, allow to boot a non secureboot (e.g. arch install ISO) from that point on?

thanks!

**Comment by adrian15** [comment]
> I have some systems with windows secureboot keys and others with custom key.
> 
> So the first question is if i can simply sign the EFI file with the custom key too?
> 
> Then does the grub2 boot process, after booting into secureboot, allow to boot a non secureboot (e.g. arch install ISO) from that point on?
> 
> thanks!

I'm using upstream Grub as a base.
If it detects that it's booting in a Secure Boot environment (no matter what key has signed the image) it will ensure that the kernel has been properly signed.

So no, you wouldn't be able to boot into a non secureboot iso.

If you want that behaviour (booting non secureboot isos, kernels or whatever) you would need to change that behaviour in grub sources and do your own unsecure build of grub (either adding the SG2D scripts or not).

Just turning off the Secure Boot checks on the UEFI firmware might be easier.

**Comment by gcb** [comment]
thank you!
